import { overrideMimeType } from 'stream-http/lib/capability';

const data = {
    status: "success",
    items: [
        {
            id: 1,
            name: "colar",
            image: require('../assets/produtos/choker.jpeg'),
            image3: require('../assets/tamanhos-colar.webp'),
            title: "CHOKER PONTO DE LUZ",
            price: "79,99",
            priceNow: "59,99",
            overview: "Choker Ponto de Luz 40cm. Um colar com um design exclusivo e com cada detalhe pensado para completar e trazer mais beleza ao estilo de cada mulher.",
            parcel: "5x de R$ 11,99",
            buy: "https://wa.link/f4z9yt"
        },
        {
            id: 2,
            name: "colar",
            image: require('../assets/produtos/colar-bolinha.jpeg'),
            image2: require('../assets/produtos/colar-bolinhas2.jpeg'),
            image3: require('../assets/tamanhos-colar.webp'),
            title: "COLAR BOLINHA",
            price: "99,99",
            priceNow: "80,99",
            overview: "Colar Bolinha 38 + 5cm. Componha seu look de forma diferenciada e arrase por onde for com nosso colar.",
            parcel: "5x de R$ 16,50",
            buy: "https://wa.link/4q8a0l"
        },
        {
            id: 3,
            name: "colar",
            image: require('../assets/produtos/colar-fe.jpeg'),
            image3: require('../assets/tamanhos-colar.webp'),
            title: "COLAR PRATA FÉ",
            price: "89,99",
            priceNow: "79,99",
            overview: "Colar Prata Fé. Aquela joia que vai te conquistar, um modelo simples e delicado. Um lembrete diário para carregar junto ao coração.",
            parcel: "5x de R$ 15,60",
            buy: "https://wa.link/lisc25"
        },
        {
            id: 4,
            name: "colar",
            image: require('../assets/produtos/corrente-lua.jpeg'),
            image2: require('../assets/produtos/corrente-lua2.jpeg'),
            image3: require('../assets/tamanhos-colar.webp'),
            title: "CORRENTE LUA",
            price: "139,99",
            priceNow: "114,99",
            overview: "Corrente Pingente de Lua 45cm. Uma joia que lembra o céu, o lugar mais lindo e misterioso que temos, essa prata com certeza irá lhe admirar.",
            parcel: "5x de R$ 22,99",
            buy: "https://wa.link/haue93"
        },
        {
            id: 5,
            name: "brinco",
            image: require('../assets/produtos/argola.jpeg'),
            title: "ARGOLA MEIA CANA",
            price: "69,99",
            priceNow: "55,99",
            overview: "Argola Meia Cana Grossa 2cm. O brinco de argola em prata é uma peça queridinha e indispensável no porta-joias.",
            parcel: "5x de 11,20",
            buy: "https://wa.link/z6i5rv"
        },
        {
            id: 6,
            name: "piercing",
            image: require('../assets/produtos/piercing.jpeg'),
            title: "PIERCING PALITO",
            price: "99,99",
            priceNow: "85,99",
            overview: "Piercing Palito Com Estrela. Perfeito para quem gosta de looks ousados e modernos. Design minimalista perfeito para montar diversas combinações incríveis, inspire-se e surpreenda-se",
            parcel: "5x de 17,20",
            buy: "https://wa.link/niwkzq"
        },
        {
            id: 7,
            name: "masculino",
            image: require('../assets/produtos/corrente-masc.jpeg'),
            image2: require('../assets/produtos/corrente-masc-70cm2.jpeg'),
            image3: require('../assets/tamanhos-colar.webp'),
            title: "CORRENTE MASCULINA 70CM",
            price: "159,99",
            priceNow: "139,99",
            overview: "Corrente Masculina 70cm. Os colares de corrente transformam qualquer visual básico, deixando você super estiloso e com presença.",
            parcel: "5x de 27,99",
            buy: "https://wa.link/dffqji"
        },
        {
            id: 8,
            name: "anel",
            image: require('../assets/produtos/anel-liso.jpeg'),
            image2: require('../assets/produtos/anel-liso2.JPG'),
            title: "ANEL TRIÂNGULO LISO",
            price: "49,99",
            priceNow: "38,99",
            overview: "Anel de Prata Triângulo Liso 14cm. Com um design liso e simples, o anel se encaixa perfeitamente em qualquer look e ocasião.",
            parcel: "5x de 7,80",
            buy: "https://wa.link/ff6lqk"
        },
        {
            id: 9,
            name: "brinco",
            image: require('../assets/produtos/brinco-ponto.jpeg'),
            title: "BRINCO PONTO DE LUZ",
            price: "59,99",
            priceNow: "46,50",
            overview: "Brinco Ponto de Luz Quadrado 9x9. Com certeza esse será o brinco favorito da sua coleção, se encaixa a qualquer ambiente, dia a dia, festas, trabalho(leve, básico e confortável",
            parcel: "5x de 9,30",
            buy: "https://wa.link/e7p04t" 
        },
        {
            id: 10,
            name: "brinco",
            image: require('../assets/produtos/brinco-trio-coracao.jpeg'),
            title: "BRINCO TRIO CORAÇÃO",
            price: "75,99",
            priceNow: "62,99",
            overview: "Brinco Trio Coração Zircônia. Com tamanhos em 4mm / 6mm / 8mm. O brinco é o toque final que ilumina o meu estilo, um detalhe que não pode faltar no seu look.",
            parcel: "5x de 12,60",
            buy: "https://wa.link/32uugj"
        },
        {
            id: 11,
            name: "brinco",
            image: require('../assets/produtos/brinco-trio-cor.jpeg'),
            title: "BRINCO TRIO COLORIDO",
            price: "59,99",
            priceNow: "46,99",
            overview: "Brinco Trio Corações Colorido. Com tamanho de 4mm. Brilhe com confiança, use um brinco como uma coroa de estilo!, se tem um brinco que que te surpreenderá em belza, com certeza é esse.",
            parcel: "5x de 9,40",
            buy: "https://wa.link/hobdlw"
        },
        {
            id: 12,
            name: "brinco",
            image: require('../assets/produtos/brinco-trio-rosa.jpeg'),
            title: "BRINCO TRIO ROSA",
            price: "59,99",
            priceNow: "49,99",
            overview: "Brinco Trio Corações Zircônias Coloridos Com tamanhos - 4mm / 5mm / 6mm. Um brinco pode transformar não apenas a sua aparência, mas também a sua confiança e atitude.",
            parcel: "5x de 9,99",
            buy: "https://wa.link/azhnzs"
        },
        {
            id: 13,
            name: "brinco",
            image: require('../assets/produtos/brinco-duplinha.jpeg'),
            title: "BRINCO DUPLO PONTO DE LUZ",
            price: "64,99",
            priceNow: "49,99",
            overview: "Brinco Duplinha Ponto de Luz. Com tamanhos em 6mm. Uma pequena joia que reflete sua personalidade ousada!",
            parcel: "5x de 9,99",
            buy: "https://wa.link/u5gcap"
        },
        {
            id: 14,
            name: "brinco",
            image: require('../assets/produtos/argola-lisa.jpeg'),
            title: "ARGOLA LISA",
            price: "149,99",
            priceNow: "126,99",
            overview: "Argola Lisa 55mm. Uma argola é mais do que uma joia, é uma declaração de estilo e uma expressão de personalidade.",
            parcel: "5x de 25,40",
            buy: "https://wa.link/q7sye3"
        },
        {
            id: 15,
            name: "brinco",
            image: require('../assets/produtos/brinco-luz-coracao.jpeg'),
            title: "BRINCO CORAÇÃO",
            price: "44,99",
            priceNow: "33,99",
            overview: "Brinco Ponto de Luz Coração. O brinco é o toque de estilo que completa o seu visual, essa joia não pode ficar de fora da sua coleção.",
            parcel: "5x de 6,80",
            buy: "https://wa.link/4h86xt"
        },
        {
            id: 16,
            name: "anel",
            image: require('../assets/produtos/anel-4-fio.jpeg'),
            image2: require('../assets/produtos/anel-4-fio2.jpeg'),
            title: "ANEL 4 FIOS",
            price: "149,99",
            priceNow: "123,99",
            overview: "Anel 4 Fios 3 Zircônias Coloridas, com tamanho de 16cm. Um anel é o símbolo do seu poder interior e da sua elegância exterior.",
            parcel: "5x de 24,80",
            buy: "https://wa.link/b7tvuf"
        },
        {
            id: 17,
            name: "anel",
            image: require('../assets/produtos/anel-dois-coracoes.jpeg'),
            image2: require('../assets/produtos/anel-dois-coracoes2.JPG'),
            title: "ANEL DOIS CORAÇÕES",
            price: "119,99",
            priceNow: "104,99",
            overview: "Anel Dois Corações Entrelaçados, com tamanhode 16cm. Seu anel é o símbolo do seu poder e elegância, uma joia que brilha com a sua personalidade.",
            parcel: "5x de 20,99",
            buy: "https://wa.link/en2wdk"
        },
        {
            id: 18,
            name: "tornozeleira",
            image: require('../assets/produtos/tornozeleira-bolinhas.jpeg'),
            image2: require('../assets/produtos/tornozeleira2.jpeg'),
            title: "TORNOZELEIRA COM BOLINHAS",
            price: "79,99",
            priceNow: "68,99",
            overview: "Tornozeleira com Bolinhas, com tamanho de 25cm. A tornozeleira é a sua liberdade em movimento, uma lembrança constante de que você segue seu próprio caminho.",
            parcel: "5x de 13,80",
            buy: "https://wa.link/g0q8ut"
        },
        {
            id: 19,
            name: "anel",
            image: require('../assets/produtos/anel-infinito.jpeg'),
            image2: require('../assets/produtos/anel-infinito2.JPG'),
            title: "ANEL INFINITO",
            price: "59,99",
            priceNow: "43,99",
            overview: "Anel Infinito - 16cm. O anel é a joia que marca seu compromisso com o amor, uma promessa eterna gravada em metal precioso.",
            parcel: "5x de 8,80",
            buy: "https://wa.link/stz98z"
        },
        {
            id: 20,
            name: "berloque",
            image: require('../assets/produtos/berloque-tabua.jpeg'),
            title: "BERLOQUE TÁBUA",
            price: "69,99",
            priceNow: "56,99",
            overview: "Berloque Tábua com Faca. Pequenos detalhes, grandes lembranças, adquira berloques e eternize momentos!",
            parcel: "5x de 11,40",
            buy: "https://wa.link/2usxeu"
        },
        {
            id: 21,
            name: "berloque",
            image: require('../assets/produtos/berloque-pedras.jpeg'),
            title: "BERLOQUE PEDRA CLARA",
            price: "75,99",
            priceNow: "64,99",
            overview: "Berloque com Pedra Clara. Os berloques são como pequenos tesouros que contam a história da sua vida, eternize cada momento com um!",
            parcel: "5x de 12,99",
            buy: "https://wa.link/ec69ud"
        },
        {
            id: 22,
            name: "berloque",
            image: require('../assets/produtos/berloque-pedras.jpeg'),
            title: "BERLOQUE PEDRA COLORIDA",
            price: "75,99",
            priceNow: "64,99",
            overview: "Berloque com Pedra Colorida. Pequenos detalhes, grandes histórias. Complete sua pulseira com nossos encantadores berloques.",
            parcel: "5x de 12,99",
            buy: "https://wa.link/m0o1wg"
        },
        {
            id: 23,
            name: "anel",
            image: require('../assets/produtos/anel-coracao.jpeg'),
            title: "ANEL CORAÇÃO",
            price: "99,99",
            priceNow: "79,99",
            overview: "Anel Coração com Bolinhas Lisas - 19cm. Este anel não é apenas uma joia, é uma promessa que você faz a si mesma de sempre lembrar do seu valor e do seu potencial.",
            parcel: "5x de 15,99",
            buy: "https://wa.link/swfmqu"
        },
        {
            id: 24,
            name: "anel",
            image: require('../assets/produtos/anel-quadrado.jpeg'),
            image2: require('../assets/produtos/anel-quadrado2.JPG'),
            title: "ANEL QUADRADO",
            price: "81,99",
            priceNow: "61,99",
            overview: "Anel Quadrado - 16cm. O seu anel não é apenas uma joia, é uma extensão da sua história, um tesouro que carrega consigo em todos os momentos.",
            parcel: "5x de 12,40",
            buy: "https://wa.link/y6l80v"
        },
        {
            id: 25,
            name: "anel",
            image: require('../assets/produtos/anel-v.jpeg'),
            title: "ANEL V",
            price: "64,99",
            priceNow: "51,99",
            overview: "Anel V com Bolinhas - 19cm. O seu anel é uma expressão de amor próprio e confiança, uma joia que ilumina sua jornada.",
            parcel: "5x de 10,40",
            buy: "https://wa.link/835yne"
        },
        {
            id: 26,
            name: "infantil",
            image: require('../assets/produtos/infantil1.jpeg'),
            title: "PULSEIRA INFANTIL",
            price: "59,99",
            priceNow: "40,99",
            overview: "Pulseira Feminina Infantil 1,1GR. Uma pulseira é um tesouro que carrega as memórias mais doces da infância, uma joia que acompanha as aventuras de quem mais amamos.",
            parcel: "5x de 8,20",
            buy: "https://wa.link/hdvwrq"
        },
        {
            id: 27,
            name: "anel",
            image: require('../assets/produtos/anel-5-coracoes.jpeg'),
            title: "ANEL 5 CORAÇÕES",
            price: "59,99",
            priceNow: "44,99",
            overview: "Anel 5 Corações Lisos - 16cm. Um anel é mais do que uma simples joia, é uma história de amor, um compromisso com a beleza e uma celebração da vida.",
            parcel: "5x de 8,99",
            buy: "https://wa.link/6jrkrj"
        },
        {
            id: 28,
            name: "anel",
            image: require('../assets/produtos/anel-no.jpeg'),
            image2: require('../assets/produtos/anel-no2.jpeg'),
            title: "ANEL LISO NÓ",
            price: "79,99",
            priceNow: "67,99",
            overview: "Anel Liso Nó - 16cm. Um anel é um círculo de amor que envolve nosso coração, uma joia que simboliza nossas conexões mais preciosas, esse é um anel que não pode faltar em sua coleção.",
            parcel: "5x de 13,60",
            buy: "https://wa.link/bpsojz"
        },
        {
            id: 29,
            name: "anel",
            image: require('../assets/produtos/anel-torcido.jpeg'),
            image2: require('../assets/produtos/anel-torcido2.jpeg'),
            title: "ANEL TORCIDO",
            price: "74,99",
            priceNow: "58,99",
            overview: "Anel Torcido - 16cm. Com um anel, não apenas adornamos nossos dedos, mas também celebramos nossa individualidade e expressamos nossa personalidade de forma única e elegante, com certeza esse anel é a sua cara.",
            parcel: "5x de 11,80",
            buy: "https://wa.link/evulx0"
        },
        {
            id: 30,
            name: "pulseira",
            image: require('../assets/produtos/pulseira-bolinhas.jpeg'),
            title: "PULSEIRA FEMININA",
            price: "89,99",
            priceNow: "73,99",
            overview: "Pulseira Feminina de Bolinhas. Sua pulseira é mais do que um acessório, é uma extensão da sua personalidade, uma peça que conta a nossa história e acompanha os momentos mais especiais da vida. Aproveite seus momentos com DelPlata.",
            parcel: "5x de 14,80",
            buy: "https://wa.link/43hb2n"
        },
        {
            id: 31,
            name: "pulseira",
            image: require('../assets/produtos/pulseira-bolas.jpeg'),
            title: "PULSEIRA FEMININA",
            price: "129,99",
            priceNow: "118,99",
            overview: "Pulseira Feminina de Bolas. Uma pulseira é a escolha perfeita para quem quer adicionar um toque de estilo e sofisticação a qualquer look, enquanto carrega consigo um símbolo de história e significado. Simbolize sua história com um produto DelPlata.",
            parcel: "5x de 23,80",
            buy: "https://wa.link/ge3e98"
        },
        {
            id: 32,
            name: "pulseira",
            image: require('../assets/produtos/pulseira-olho-grego.jpeg'),
            title: "PULSEIRA OLHO GREGO",
            price: "69,99",
            priceNow: "51,99",
            overview: "Pulseira Olho Grego. Com a pulseira de olho grego, você se sente protegido e envolvido por energias positivas, pronto para enfrentar qualquer desafio com confiança.",
            parcel: "5x de 10,40",
            buy: "https://wa.link/s1nuog"
        },
        {
            id: 33,
            name: "masculino",
            image: require('../assets/produtos/corrente-masc-60cm.jpeg'),
            image2: require('../assets/produtos/corrente-masc-60cm3.jpeg'),
            image3: require('../assets/tamanhos-colar.webp'),
            title: "CORRENTE MASCULINA 60CM",
            price: "139,99",
            priceNow: "115,99",
            overview: "Corrente Masculina 60cm 4GR. Uma corrente pode ser mais do que um acessório de moda, pode ser uma peça de valor duradouro que acrescenta um toque de elegância e sofisticação a qualquer visual. Compre uma corrente de alta qualidade hoje e você poderá desfrutar dela por anos.",
            parcel: "5x de 23,50",
            buy: "https://wa.link/izyk53" 
        },
        {
            id: 34,
            name: "pulseira",
            image: require('../assets/produtos/pulseira-3-flores.jpeg'),
            image2: require('../assets/produtos/pulseira-3-flores2.jpeg'),
            title: "PULSEIRA 3 FLORES",
            price: "89,99",
            priceNow: "70,99",
            overview: "Pulseira 3 Flores - 20cm. Uma pulseira pode ser o toque final perfeito para qualquer look, seja casual ou formal. Compre uma pulseira que reflita sua personalidade e estilo, e você terá uma peça única que pode ser apreciada por anos.",
            parcel: "5s de 14,20",
            buy: "https://wa.link/1bg4z2"
        },
        {
            id: 35,
            name: "pulseira",
            image: require('../assets/produtos/pulseira-folha.jpeg'),
            image2: require('../assets/produtos/pulseira-folha2.jpeg'),
            title: "PULSEIRA FOLHA",
            price: "69,99",
            priceNow: "53,99",
            overview: "Pulseira Folha - 18.5cm. Uma pulseira pode ser o detalhe que faltava para complementar o seu look e torná-lo ainda mais elegante e sofisticado. Invista em uma pulseira de qualidade e tenha a certeza de estar adicionando um toque de charme e estilo ao seu visual.",
            parcel: "5x de 10,80",
            buy: "https://wa.link/h1hle9"
        },
        {
            id: 36,
            name: "pulseira",
            image: require('../assets/produtos/pulseira-borboleta.jpeg'),
            image2: require('../assets/produtos/pulseira-borboleta2.jpeg'),
            title: "PULSEIRA BORBOLETA",
            price: "67,99",
            priceNow: "54,99",
            overview: "Pulseira Borboleta - 18.5cm. Uma pulseira é mais do que um simples acessório - ela pode ser uma maneira de expressar sua personalidade e estilo. Além disso, uma pulseira bem escolhida pode ser um presente perfeito para alguém especial em sua vida.",
            parcel: "5x de 11,20",
            buy: "https://wa.link/egsd73"
        },
        {
            id: 37,
            name: "anel",
            image: require('../assets/produtos/anel-estrela.jpeg'),
            image2: require('../assets/produtos/anel-estrela2.jpeg'),
            title: "ANEL ESTRELA",
            price: "49,99",
            priceNow: "35,99",
            overview: "Anel Estrela Lisa - 16cm. Um anel é mais do que uma joia, é uma lembrança dos momentos especiais que carrega com si mesma. Invista em um anel de alta qualidade e duradouro, e você estará criando um tesouro para toda a vida.",
            parcel: "5x de 7,50",
            buy: "https://wa.link/8l8w3e"
        },
        {
            id: 38,
            name: "anel",
            image: require('../assets/produtos/anel-seta.jpeg'),
            image2: require('../assets/produtos/anel-seta2.jpeg'),
            title: "ANEL SETA",
            price: "59,99",
            priceNow: "41,99",
            overview: "Anel Seta de Lado - 17cm. O anel seta é uma escolha elegante e sofisticada que adiciona um toque de brilho sutil às suas mãos. Além disso, sua durabilidade e resistência a manchas garantem que você possa apreciar seu brilho impecável por muitos anos.",
            parcel: "5x de 8,40",
            buy: "https://wa.link/cfg1w2"
        },
        {
            id: 39,
            name: "anel",
            image: require('../assets/produtos/anel-coracao-vazado.jpeg'),
            image2: require('../assets/produtos/anel-coracao-vazado2.jpeg'),
            title: "ANEL CORAÇÃO VAZADO",
            price: "89,99",
            priceNow: "71,99",
            overview: "Anel de Prata, Coração Vazado - 16cm. O anel coração vazado é uma escolha elegante e sofisticada para quem procura uma peça de joalheria durável e atemporal, com a sua elegância, ele pode ser usado em qualquer ocasião, adicionando aquele toque final no look.",
            parcel: "5x de 14,40",
            buy: "https://wa.link/vn4t97"
        },
        {
            id: 40,
            name: "anel",
            image: require('../assets/produtos/anel-coracao-liso.jpeg'),
            image2: require('../assets/produtos/anel-coracao-liso2.jpeg'),
            title: "ANEL TORCIDO CORAÇÃO",
            price: "79,99",
            priceNow: "56,99",
            overview: "Anel de Prata com Aro Torcido e Coração Liso - 16cm. O anel coração é elegante, sofisticado e atemporal. Sua beleza discreta e durabilidade tornam-no uma escolha clássica e versátil para qualquer ocasião.",
            parcel: "5x de 11,40",
            buy: "https://wa.link/vn4t97"
        },
        {
            id: 41,
            name: "anel",
            image: require('../assets/produtos/anel-love.jpeg'),
            image2: require('../assets/produtos/anel-love2.jpeg'),
            title: "ANEL LOVE",
            price: "59,99",
            priceNow: "45,99",
            overview: "Anel Love - 19cm. Com seu brilho único e acabamento impecável, o anel Love acrescenta um toque de classe e distinção a qualquer ocasião. Além disso, sua durabilidade e resistência o tornam uma escolha prática e acessível para quem procura um acessório de alta qualidade.",
            parcel: "5x de 9,20",
            buy: "https://wa.link/ztlxca"
        },
        {
            id: 42,
            name: "anel",
            image: require('../assets/produtos/anel-coracao-infinito.jpeg'),
            image2: require('../assets/produtos/anel-coracao-infinito2.jpeg'),
            title: "ANEL CORAÇÃO INFINITO",
            price: "55,99",
            priceNow: "41,99",
            overview: "Anel Coração Infinito - 16 e 19cm. O anel Coração Infinito é uma escolha elegante e sofisticada para quem procura uma joia versátil e atemporal. Além disso, o anel pode ser facilmente combinado com outras peças de joalheria, tornando-o um item indispensável para qualquer guarda-roupa.",
            parcel: "5x de 8,40",
            buy: "https://wa.link/vww0u9"
        },
        {
            id: 43,
            name: "colar",
            image: require('../assets/produtos/corrente-laminada.jpeg'),
            title: "CORRENTE LAMINADA",
            price: "149,99",
            priceNow: "135,99",
            overview: "Corrente Laminada - 45cm. Uma corrente é mais do que um acessório, é uma expressão da sua personalidade e estilo. É a forma perfeita de realçar a sua beleza e marcar presença por onde passa. Marque presença usando Del Plata.",
            parcel: "5x de 27,20",
            buy: "https://wa.link/t2i6xm"
        },
        {
            id: 44,
            name: "masculino",
            image: require('../assets/produtos/pulseira-masc-20cm.jpeg'),
            title: "PULSEIRA MASCULINA",
            price: "109,99",
            priceNow: "93,99",
            overview: "Pulseira Masculina - 20cm. - 3,2GR. Uma pulseira é mais do que um simples adorno, é um símbolo de elegância, sofisticação e personalidade. Invista em uma pulseira de qualidade e eleve o seu estilo a um novo patamar.",
            parcel: "5x de 18,80",
            buy: "https://wa.link/job6ys"
        },
        {
            id: 45,
            name: "masculino",
            image: require('../assets/produtos/pulseira-masc2.jpeg'),
            title: "PULSEIRA MASCULINA",
            price: "94,99",
            priceNow: "81,99",
            overview: "Pulseira Masculina - 20cm. Um acessório que complementa o seu visual, tornando-o ainda mais charmoso e marcante. Seja para ocasiões formais ou informais, a pulseira certa é o toque final para um look perfeito",
            parcel: "5x de 16,40",
            buy: "https://wa.link/yleyb0"
        },
        {
            id: 46,
            name: "masculino",
            image: require('../assets/produtos/pulseira-masc3.jpeg'),
            title: "PULSEIRA MASCULINA",
            price: "159,99",
            priceNow: "134,99",
            overview: "Pulseira Masculina - 21cm. Uma pulseira é mais do que um simples adorno, é uma peça que carrega consigo sentimentos e memórias que te acompanharão para sempre. Carregue a sua história com a Del Plata",
            parcel: "5x de 27,00",
            buy: "https://wa.link/9p10d3"
        },
        {
            id: 47,
            name: "masculino",
            image: require('../assets/produtos/pulseira-masc4.jpeg'),
            title: "PULSEIRA MASCULINA",
            price: "109,99",
            priceNow: "96,99",
            overview: "Pulseira Masculina - 21cm. Um objeto que representa a sua personalidade e história, além de ser uma forma de expressão única que demonstra o seu estilo e bom gosto. Adquira agora a sua pulseira e sinta a emoção de ter um acessório que irá te acompanhar em todos os momentos da sua vida.",
            parcel: "5x de 19,40",
            buy: "https://wa.link/4h5aq4"
        }
    ],
};
export default data;